#!/bin/sh

usage() {
    echo "Usage: $(basename $0) [options] <remote> <refs...>"
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "--no-branches"
    echo "--no-tags"
    exit $1
}

opts=$(getopt --options "h" --longoptions "help,no-branches,no-tags" --name "$(basename $0)" -- "$@") || usage 1
eval set -- "$opts"

set -e

branches=true
tags=true

while true; do
    case "$1" in
        -h|--help)
            usage 0
            ;;
        --no-branches)
            branches=false
            shift
            ;;
        --no-tags)
            tags=false
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

[ $# -lt 2 ] && usage 1

remote=$1
shift

for ref in "$@"; do
    refs=()
    if $branches; then
        branches+=($(git branch -r | grep -E "$remote/" | cut -d/ -f2))
        for branch in "${branches[@]}"; do
            if [[ $branch == $ref ]]; then
                refs+=($branch)
            fi
        done
    fi
    if $tags; then
        tags=($(git ls-remote --tags "$remote" | grep -v '\^{}' | awk '{print $2}' | sed 's/refs\/tags\///'))
        for tag in "${tags[@]}"; do
            if [[ $tag == $ref ]]; then
                refs+=($tag)
            fi
        done
    fi
    if [ ${#refs[@]} -eq 0 ]; then
        echo "No refs match $ref"
    else
        git push $remote --delete "${refs[@]}"
    fi
done
