#!/bin/sh

set -e

x=false

opts=()
while [ $# -gt 0 ]; do
    case "$1" in
        -x)
            x=true
            shift
            ;;
        -m|--manifest-name)
            args+=("$1" $(realpath "$2"))
            shift 2
            ;;
        -m=*|--manifest-name=*)
            args+=("${1%=*}"=$(realpath "${1#*=}"))
            shift
            ;;
        *)
            opts+=("$1")
            shift
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo init ${args[@]} ${opts[@]}"
else
    repo init ${opts[@]}
fi
