#!/bin/bash

function usage() {
    echo "Usage: $(basename $0) [options] [<projects>] [<files>]"
    echo ""
    echo "Unignores files for 'repo status' for all/specified projects."
    echo ""
    echo "For example:"
    echo "$ $(basename $0) package-lock.json"
    echo ""
    echo "Options:"
    echo "-h,--help"
    exit $1
}

opts=$(getopt --options "h" --longoptions "help" --name "$(basename $0)" -- "$@") || usage 1
eval set -- "$opts"

set -e

while true; do
    case "$1" in
        -h|--help)
            usage 0
            ;;
        --)
            shift
            break
            ;;
    esac
done

function is_project() {
    repo list -n | grep -q -w -F "$1"
}

projects=()
patterns=()
for opt in "$@"; do
    if is_project "$opt"; then
        projects+=("$opt")
    else
        patterns+=("$opt")
    fi
done

patterns=$(echo "${patterns[@]}" | sed 's/ /\\|/g')
if [ -n "$patterns" ]; then
    repo forall "${projects[@]}" -c 'git ls-files | grep -E "'$patterns'" | xargs git update-index --no-assume-unchanged'
else
    repo forall "${projects[@]}" -c 'git ls-files -v | grep "^[[:lower:]]" | cut -c3- | xargs git update-index --no-assume-unchanged'
fi
