#!/bin/bash

set -e

repo_mirror_location=${REPO_MIRROR_LOCATION:-$PWD}

function usage() {
    echo "Usage: $(basename $0) [options]"
    echo ""
    echo "Runs 'repo-sync' and 'repo-lfs-fetch' in \$REPO_MIRROR_LOCATION (or"
    echo "\$PWD if not set). Furthermore, if no '.repo' directory is found, runs"
    echo "'repo-init --mirror' to set up a new mirror."
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "-j,--jobs <jobs>"
    exit $1
}

for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
    esac
done

if [ ! -d "$repo_mirror_location/.repo" ]; then
    mkdir -p "$repo_mirror_location"
    cd "$repo_mirror_location"
    repo-init --mirror
else
    cd "$repo_mirror_location"
fi

echo "Syncing $repo_mirror_location..."
repo-sync "$@"
repo-lfs-fetch "$@"
