#!/bin/sh

set -ex

x=false

opts=()
for opt in "$@"; do
    case "$opt" in
        -x)
            x=true
            ;;
        *)
            opts+=("$opt")
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo sync -c --retry-fetches=5 --no-tags ${opts[@]}"
else
    repo sync -c --retry-fetches=5 --no-tags ${opts[@]}
fi
