#!/bin/bash

dir="$(realpath ${1:-$PWD})"
cur="$dir"
while [ -d "$cur" ] && [ "$cur" != "/" ]; do
    if [ -d "$cur/.repo" ]; then
        echo "$cur"
        exit 0
    fi
    cur=$(dirname "$cur")
done

echo "ERROR: not a repo tree: $dir" >&2
exit 1
