#!/bin/sh

set -e

opts=()
while [ $# -gt 0 ]; do
    case "$1" in
        -m|--manifest-name)
            args+=("$1" $(realpath "$2"))
            shift 2
            ;;
        -m=*|--manifest-name=*)
            args+=("${1%=*}"=$(realpath "${1#*=}"))
            shift
            ;;
        *)
            opts+=("$1")
            shift
            ;;
    esac
done

repo sync -c --retry-fetches=5 --no-tags ${opts[@]}
