#!/bin/sh

set -e

verbose=false
x=false

function usage() {
    echo "Usage: $(basename $0) [options] [projects]"
    echo ""
    echo "Runs 'git lfs pull' in all/specified projects."
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "-v,--verbose"
    echo "-x"
    exit $1
}

opts=""
for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        -v|--verbose)
            verbose=true
            ;;
        -x)
            x=true
            ;;
        *)
            opts="$opts $opt"
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo forall $opts -c 'git lfs pull'"
elif [ $verbose = true ]; then
    repo forall $opts -c 'echo -e "\r\033[KLFS pull: $(($REPO_I*100/$REPO_COUNT))% ($REPO_I/$REPO_COUNT) $REPO_PROJECT" && git lfs pull'
else
    repo forall $opts -c 'echo -ne "\r\033[KLFS pull: $(($REPO_I*100/$REPO_COUNT))% ($REPO_I/$REPO_COUNT) $REPO_PROJECT" && git lfs pull' && echo
fi
