#!/bin/sh

function usage() {
    echo "Usage: $(basename $0) [options] <files>"
    echo ""
    echo "Ignores files for 'repo-status'."
    echo ""
    echo "For example:"
    echo "$ $(basename $0) package-lock.json"
    echo ""
    echo "Options:"
    echo "-h,--help"
    exit $1
}

opts=$(getopt --options "h" --longoptions "help" --name "$(basename $0)" -- "$@") || usage 1
eval set -- "$opts"

set -e

while true; do
    case "$1" in
        -h|--help)
            usage 0
            ;;
        --)
            shift
            break
            ;;
    esac
done

[ $# -gt 0 ] || usage 1

patterns=$(echo "$@" | sed 's/ /\\|/g')
repo forall -c 'git ls-files | grep -E '$patterns' | xargs git update-index --assume-unchanged'
