#!/bin/sh

set -e

function usage() {
    echo "Usage: $(basename $0) [options]"
    echo ""
    echo "Runs 'git clean' in all projects."
    echo ""
    echo "For example:"
    echo "$ $(basename $0) -xdf"
    echo ""
    echo "Options:"
    echo "-h,--help"
    exit $1
}

opts=()
for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        *)
            opts+=("$opt")
            ;;
    esac
done

repo forall -c "git clean ${opts[@]}" --
