#!/bin/sh

set -e

x=false

function usage() {
    echo "Usage: $(basename $0) [options]"
    echo ""
    echo "Runs 'git reset' in all projects."
    echo ""
    echo "For example:"
    echo "$ $(basename $0) --hard"
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "-x"
    exit $1
}

opts=""
for opt in "$opts"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        -x)
            x=true
            ;;
        *)
            opts="$opts $opt"
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo forall -c 'git reset $opts' --"
else
    repo forall -c "git reset $opts" --
fi
