#!/bin/bash

function usage() {
    echo "Usage: $(basename $0) [options] [<projects>] [<remotes>]"
    echo ""
    echo "Runs 'git pull' for all/specified projects and remotes."
    echo ""
    echo "Options:"
    echo "-h,--help"
    exit $1
}

set -e

function is_project() {
    repo list -n | grep -q -w -F "$1"
}

projects=()
remotes=()
for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        *)
            if is_project "$opt"; then
                projects+=("$opt")
            else
                remotes+=("$opt")
            fi
            ;;
    esac
done

repo forall "${projects[@]}" -c '
    rr=""
    for r in '"${remotes[@]}"'; do
        if git remote | grep -q -w -F "$r"; then
            [ -z "$rr" ] && rr="$r" || rr="$rr $r"
        fi
    done
    if [ -n "$rr" ]; then
        echo "Pulling $REPO_PROJECT..."
        git pull "$rr"
    elif [ -z '"${remotes[@]}"' ]; then
        echo "Pulling $(($REPO_I*100/$REPO_COUNT))% ($REPO_I/$REPO_COUNT) $REPO_PROJECT..."
        git pull
    fi
'
