#!/bin/sh

set -e

x=false

opts=""
for opt in "$@"; do
    case "$opt" in
        -x)
            x=true
            ;;
        *)
            opts="$opts $opt"
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo init ${args[@]} $opts"
else
    repo init $opts
fi
