#!/bin/bash

function usage() {
    echo "Usage: $(basename $0) [options] [<projects>]"
    echo ""
    echo "Runs 'git diff' in all/specified projects."
    echo ""
    echo "Options:"
    echo "-h,--help"
    exit $1
}

opts=$(getopt --options "h" --longoptions "help" --name "$(basename $0)" -- "$@") || usage 1
eval set -- "$opts"

set -e

while true; do
    case "$1" in
        -h|--help)
            usage 0
            ;;
        --)
            shift
            break
            ;;
    esac
done

repo forall "$@" -p -c 'git -c color.diff=always diff'
