#!/bin/sh

set -e

x=false

function usage() {
    echo "Usage: $(basename $0) [options]"
    echo ""
    echo "Runs 'repo-sync' and 'repo-lfs-fetch' in 'REPO_X_MIRROR'."
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "-j,--jobs <jobs>"
    echo "-x"
    exit $1
}

for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        -x)
            x=true
            ;;
    esac
done

if [ $x = true ]; then
    echo "cd $REPO_X_MIRROR"
elif [ -z "$REPO_X_MIRROR" ]; then
    echo "ERROR: REPO_X_MIRROR not set" >&2
    exit 1
elif [ ! -d "$REPO_X_MIRROR" ]; then
    mkdir -p "$REPO_X_MIRROR"
    cd "$REPO_X_MIRROR"
    repo-init --mirror
else
    cd "$REPO_X_MIRROR"
fi
repo-sync "$@"
repo-lfs-fetch "$@"
