#!/bin/sh

set -e

x=false

function usage() {
    echo "Usage: $(basename $0) [options]"
    echo ""
    echo "Runs 'git clean' in all projects."
    echo ""
    echo "For example:"
    echo "$ $(basename $0) -xdf"
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "-x"
    exit $1
}

opts=()
for opt in "$@"; do
    case "$opt" in
        -h|--help)
            usage
            ;;
        -x)
            x=true
            ;;
        *)
            opts+=("$opt")
            ;;
    esac
done

if [ $x = true ]; then
    echo "repo forall -c 'git clean ${opts[@]}' --"
else
    repo forall -c "git clean ${opts[@]}" --
fi
